version: "3.4"
services:
  nginx:
    build: './docker/nginx/'
    container_name: nginx
    restart: always
    depends_on:
      - php
      - mariadb
      - supervisor
    networks:
      - frontend
      - backend
    ports:
      - "6969:80"
    volumes:
      - ./:/var/www/html/
  php:
    build:
      context: './docker/php/'
      target: php
    container_name: php7.4
    restart: always
    networks:
      - backend
    volumes:
      - ./:/var/www/html/
      - ./docker/php/config/config.ini:/usr/local/etc/php/conf.d/uploads.ini
  cronjob:
    build:
      context: './docker/php/'
      target: cron
    container_name: cronjob
    restart: always
    networks:
      - backend
    volumes:
      - ./:/var/www/html/
      - ./docker/php/config/config.ini:/usr/local/etc/php/conf.d/uploads.ini
  supervisor:
    build:
      context: './docker/php/'
      target: queue
    container_name: supervisor
    restart: always
    networks:
      - backend
    volumes:
      - ./:/var/www/html/
      - ./docker/php/config/config.ini:/usr/local/etc/php/conf.d/uploads.ini
  mariadb:
    image: mariadb
    container_name: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: 'always'
    ports:
      - "33066:3306"
    networks:
      - backend
    volumes:
      - ./:/var/www/html/
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=10
      - PMA_HOST=mariadb
      - PMA_PORT=3306

    restart: always
    ports:
      - "18882:80"
    networks:
      - backend

networks:
  frontend:
  backend:
