version: "3.3"
services:
  php:
    build: './php/'
    container_name: php7.3
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/
  apache:
    build: './apache/'
    container_name: apache2.4
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./public_html/:/var/www/html/
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test_db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
networks:
  frontend:
  backend:
