version: "3.3"
services:
  php:
    build: './php/'
    container_name: php7.4
    networks:
      - backend
    volumes:
      - ./source/:/var/www/html/
      - ./php/config/config.ini:/usr/local/etc/php/conf.d/uploads.ini
  supervisor:
    build: './supervisor/'
    container_name: supervisor
    networks:
      - backend
    volumes:
      - ./source/:/var/www/html/
      - ./php/config/config.ini:/usr/local/etc/php/conf.d/uploads.ini
  cronjob:
    build: './cronjob/'
    container_name: cronjob
    networks:
      - backend
    volumes:
      - ./source/:/var/www/html/
      - ./php/config/config.ini:/usr/local/etc/php/conf.d/uploads.ini
  apache:
    build: './apache/'
    container_name: apache2.4
    depends_on:
      - php
      - mysql
      - supervisor
    networks:
      - frontend
      - backend
    ports:
      - "8088:80"
    volumes:
      - ./source/:/var/www/html/
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "33066:3306"
    networks:
      - backend
    volumes:
      - ./source/:/var/www/html/
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ramen
      MYSQL_USER: miichi
      MYSQL_PASSWORD: 123456
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=10
      - PMA_HOST=mysql
      - PMA_PORT=3306

    restart: always
    ports:
      - "18882:80"
    networks:
      - backend

networks:
  frontend:
  backend:
