version: "3.3"
services:
  php:
    build: './php/'
    container_name: ramen_php7.3
    networks:
      - backend
    volumes:
      - ./source/:/var/www/html/
      - ./php/config/config.ini:/usr/local/etc/php/conf.d/uploads.ini
  apache:
    build: './apache/'
    container_name: ramen_apache2.4
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./source/:/var/www/html/
  mysql:
    image: mysql:8.0
    container_name: ramen_mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ramen
      MYSQL_USER: miichi
      MYSQL_PASSWORD: 123456
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ramen_phpmyadmin
    environment:
      - PMA_ARBITRARY=10
      - PMA_HOST=ramen_mysql
      - PMA_PORT=3306

    restart: always
    ports:
      - "18082:80"
    networks:
      - backend

networks:
  frontend:
  backend:
